services:
  - type: web
    name: mrlarbin-dlive-apptoken
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DLIVE_CLIENT_ID
        sync: false
      - key: DLIVE_CLIENT_SECRET
        sync: false
      - key: DLIVE_TARGET_DISPLAYNAME
        value: skrymi
      - key: DLIVE_MESSAGE
        value: "Hello depuis MrLarbin (app token)"
      - key: PORT
        value: "10000"
    healthCheckPath: /
    autoDeploy: true
